### ISSUE TITLE
KeyError: 1.0 - Error while running XCMS input generating 'experiment'

### ISSUE THREAD

**Issue by hpbenton** [bihealth/NeatMS#2]
While generating the experiment variable from the ntms.Experiment method I get an error while loading in my own data. I've followed the XCMS R input that you have on [xcms_input_table_gen](https://neatms.readthedocs.io/en/latest/first-steps/data-format/#feature-table-export-from-xcms-aligned-peaks-with-gapfilling).

I can send data and feature_table if needed. 

```
raw_data_folder_path = '../data/neg_data/'
feature_table_path = '../data/NeatMS_aligned_feature_table.csv'

# This is important for NeatMS to read the feature table correctly
input_data = 'XCMS'

exp = ntms.Experiment(raw_data_folder_path, feature_table_path, input_data)
  2021-09-12 13:41:54,483 | INFO : Data reader backend: pymzml
  2021-09-12 13:41:54,483 | INFO : Loading file 1 / 41
  2021-09-12 13:41:54,483 | INFO : Loading file 2 / 41
  2021-09-12 13:41:54,483 | INFO : Loading file 3 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 4 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 5 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 6 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 7 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 8 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 9 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 10 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 11 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 12 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 13 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 14 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 15 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 16 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 17 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 18 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 19 / 41
  2021-09-12 13:41:54,484 | INFO : Loading file 20 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 21 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 22 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 23 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 24 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 25 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 26 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 27 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 28 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 29 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 30 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 31 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 32 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 33 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 34 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 35 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 36 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 37 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 38 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 39 / 41
  2021-09-12 13:41:54,485 | INFO : Loading file 40 / 41
  2021-09-12 13:41:54,486 | INFO : Loading file 41 / 41
  2021-09-12 13:41:54,486 | INFO : Loading feature table: /data/NeatMS_aligned_feature_table.csv
  2021-09-12 13:41:54,486 | INFO : Feature table format: XCMS
  2021-09-12 13:41:55,132 | INFO : Feature table contains aligned peaks
  2021-09-12 13:41:55,144 | INFO : Loading 14483 features and 330493 peaks 
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.9/site-packages/NeatMS/experiment.py", line 33, in __init__
      self.load_feature_table(feature_table_path, labels)
    File "/usr/local/lib/python3.9/site-packages/NeatMS/experiment.py", line 141, in load_feature_table
      feature_table.load_features(self.samples)
    File "/usr/local/lib/python3.9/site-packages/NeatMS/feature.py", line 639, in load_features
      self.load_unaligned_features(unaligned_feature_array, sample_map)
    File "/usr/local/lib/python3.9/site-packages/NeatMS/feature.py", line 492, in load_unaligned_features
      sample = sample_map[feature_array[10][entry]]
  KeyError: 1.0
```

**Comment by yoglo** [comment]
Thank you for your feedback, this is most likely an issue with the data format. 

Unless you have named your samples using numbers (1.mzml, 2.mzml etc.), it seems that the "sample_name" column contains the sample ids instead, which are normally stored in the "sample" column.

Could you please check and let me know what is stored in the "sample_name" column and in the "sample" column?

Just in case, here is how you can do that:

import pandas as pd
df = pd.read_csv(feature_table_path)
pd.set_option('display.max_columns', None)
df.head()

Thanks,
Yoann

**Comment by hpbenton** [comment]
Yep it looks like it was a conversion issue from MSnBase xcms object to the report. 
I think what you want rather than the 
``` 
# Retrieve the sample names and store them as a dataframe
sample_names_df <- as.data.frame(sampleNames(xdata_filled))
```
is

``` 
# Retrieve the sample names and store them as a dataframe
sample_names_df <- as.data.frame(basename(fileNames(xdata_filled)))
```

**Comment by yoglo** [comment]
Thank you for the feedback, the sampleNames function returns inconsistent results depending on the version apparently (this was already reported once). 
I will add your solution to the documentation, it should be fine but please make sure that the files are in the same order as given by the sampleNames function as this could have a really bad impact on the downstream processing.
